<?php

namespace App\Http\Controllers\Customization;

use App\Http\Controllers\Controller;
use App\Models\OrderItem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\Response;

class QrCodeController extends Controller
{
    /**
     * Serve a QR preview to the owner of the active customization session.
     * Access is protected by a signed temporary URL generated by the Livewire
     * component (a signature the attacker cannot forge), an expiry, and a
     * realpath guard that confines reads to the private disk. The `path` is
     * carried as a query parameter so slashes in the value never collide with
     * route segment parsing.
     */
    public function preview(Request $request): Response
    {
        $path = $request->string('path')->toString();

        return $this->serveFromLocalDisk($path);
    }

    /**
     * Serve a QR code from an order snapshot to an authenticated admin. The
     * path must exist in some OrderItem's snapshot (ownership binding) —
     * arbitrary/foreign paths resolve to 404, and the realpath guard
     * additionally confines reads inside the private disk.
     */
    public function adminShow(Request $request): Response
    {
        $path = $request->string('path')->toString();

        $ownsPath = OrderItem::query()
            ->where('customization_json->qr_code_path', $path)
            ->exists();

        if (! $ownsPath) {
            abort(404);
        }

        return $this->serveFromLocalDisk($path);
    }

    private function serveFromLocalDisk(string $path): Response
    {
        $disk = Storage::disk('local');
        $rootReal = realpath($disk->path(''));
        $rootReal = $rootReal === false ? false : rtrim($rootReal, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR;

        if ($rootReal === false) {
            abort(404);
        }

        $fileReal = realpath($disk->path($path));

        if ($fileReal === false || ! str_starts_with($fileReal, $rootReal)) {
            abort(404);
        }

        if (! $disk->exists($path)) {
            abort(404);
        }

        $name = 'qr-'.basename($path);

        return $disk->response($path, $name);
    }
}
